### ISSUE TITLE
PrintJacobian for CR3BP+LT

### ISSUE THREAD

**Issue by adcox** [adcox/pika#16]
Ran into a bug with a CR3BP+LT `ShootingProblem` that had two sets of propagation parameters defined on two segments:
```
Traceback (most recent call last):
  File "/Users/ancox/Projects/neos/tools/cr3bp+lt/./mk_halo.py", line 146, in <module>
    problem_lt.printJacobian()
  File "/Users/ancox/Projects/neos/tools/cr3bp+lt/pika/pika/corrections/__init__.py", line 993, in printJacobian
    jacobian = self.jacobian()
  File "/Users/ancox/Projects/neos/tools/cr3bp+lt/pika/pika/corrections/__init__.py", line 868, in jacobian
    self._jacobian[rix, cols] = partials
ValueError: shape mismatch: value array of shape (6,) could not be broadcast to indexing result of shape (4,)
```

**Comment by adcox** [comment]
Resolved via [0d66cf3](https://github.com/adcox/pika/commit/0d66cf3f4deec1bd30e276f04983eae8b06e8598)
